version: '3'

services:
  db:
    image: mysql
    restart: always
    platform: linux/x86_64
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
      MYSQL_DATABASE: ouvidoria_db